services:
  build:
    image: ghcr.io/williamjacksn/pelican
    init: true
    volumes:
      - ./:/home/python/blog
    working_dir: /home/python/blog

  gen-css:
    entrypoint:
      - /home/python/venv/bin/pygmentize
      - -S
      - default
      - -f
      - html
      - -a
      - .highlight
    image: ghcr.io/williamjacksn/pelican
    init: true
    volumes:
      - ./:/home/python/blog
    working_dir: /home/python/blog

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/pelican
    init: true
    volumes:
      - ./:/home/python/blog
    working_dir: /home/python/blog

  simple-serve:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - http.server
    image: ghcr.io/williamjacksn/pelican
    init: true
    ports:
      - '8000:8000'
    volumes:
      - ./:/home/python/blog
    working_dir: /home/python/blog/output
