[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "htpy>=26.5.1",
    "markdown>=3.10.3",
    "markupsafe>=3.0.3",
    "pelican>=4.12.0",
    "pelican-htpy>=2026.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.8",
    "ty>=0.0.82",
]

[tool.ruff.lint]
extend-select = ["ANN", "E", "F", "FURB", "I", "PERF", "Q", "RSE", "RUF", "S", "UP"]
